steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
#  dir: 'surveilliance-api'
  args: ['build', '-t', 'asia-docker.pkg.dev/$PROJECT_ID/disastermanagement-repo/update:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-docker.pkg.dev/$PROJECT_ID/disastermanagement/update:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'disastermanagementcloudrun'
    - '--image'
    - 'asia-docker.pkg.dev/$PROJECT_ID/disastermanagement/update:$COMMIT_SHA'
    - '--region'
    - 'asia-south2'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '1'
    - '--allow-unauthenticated'
images:
- 'asia-docker.pkg.dev/$PROJECT_ID/disastermanagement/update'
options:
  logging: CLOUD_LOGGING_ONLY